### ISSUE TITLE
New release of `pytest-profile` ? In particular for the gprof2dot fix for windows

### ISSUE THREAD

**Issue by smarie** [man-group/pytest-plugins#162]
Hi, it seems that there was no release of `pytest-profile` since #99 was merged.

Would it be possible ? The SVG file not being generated automatically is really a pain for windows users.

Thanks in advance !

**Comment by raqib-hayder** [comment]
I am having the same issue on macOS. 

@smarie : Is there an alternative way to generate the SVG?

**Comment by smarie** [comment]
You have to execute this command manually either in one stap with the pipe or in two steps with an intermediate file:

`gprof2dot -f pstats prof/combined.prof | dot -Tsvg -o prof/combined.svg`

**Comment by OverLordGoldDragon** [comment]
Still an issue.

@smarie Can your [PR](https://github.com/man-group/pytest-plugins/pull/99/files) file be pasted over the pip installation?

**Comment by jonbannister** [comment]
We have released! 🚀

**Comment by smarie** [comment]
Great !!!! Thanks a lot @jonbannister , this was long awaited :)
