### ISSUE TITLE
path.py is deprecated

### ISSUE THREAD

**Issue by maresb** [man-group/pytest-plugins#175]
As stated [here](https://pypi.org/project/path.py/), path.py has been renamed to path.

This leads to issues in other projects such as https://github.com/conda-forge/pytest-shutil-feedstock/issues/5 which expect path.py not to be used anymore.

I propose #174 as a fix.

**Comment by eeaston** [comment]
Merged, thanks for raising. I'll close this when we get a release out.

**Comment by henryiii** [comment]
This is breaking pip check for pytest-shutil -> pytest-virtualenv -> scikit-build-core on conda-forge. Any ETA on a release?

**Comment by jonbannister** [comment]
We are now using stdlib's pathlib instead across the board. Release coming soon...
