### ISSUE TITLE
Add builds for modern python versions

### ISSUE THREAD

**Issue by jonbannister** [man-group/pytest-plugins#229]
We should build at least: 3.8, 3.10, 3.11, 3.12 and aim for 3.13.

**Comment by offbyone** [comment]
Do you want PRs for this? I'm about to spend some time on a plane, and that's prime "mess around with CI" time :D

**Comment by jonbannister** [comment]
I mean - sure, why not! This is how far I got a few weeks ago https://github.com/man-group/pytest-plugins/compare/master...add-new-py-versions

**Comment by offbyone** [comment]
How wedded to the current setuptools workflow are you? Are you okay with changing up the dev environment, or is there a standard interaction you want to preserve?

I ask because lately I've been switching all my packages over to `uv` and lemme tell you... it is _nice_.

**Comment by jonbannister** [comment]
Feel free to try - I suspect there may be some custom setuptools hooks that you would need to replace. As long as the build artefacts are the same I don't mind either way :)
